### ISSUE TITLE
Attributes Delete

### ISSUE THREAD

**Issue by smschwartz** [mucsci-students/2022sp-420-AlarmSquad#15]
- [x] Ensure Attributes Add is complete
 - [x] When Delete Attribute command is entered, prompt user for class name, and an existing attribute name
 - [x] If attribute name or class name does not exist, inform user and exit Delete Attribute method
- [x] Delete attribute object in class

 - Primary: @mmoyer1
 - Secondary: @ABFoster98
 - Size: MEDIUM/LARGE
 - Actual Size: TBA
 - Actual Time: TBA

**Comment by mmoyer1** [comment]
finished for now
