### ISSUE TITLE
Parameters

### ISSUE THREAD

**Issue by mmoyer1** [mucsci-students/2022sp-420-AlarmSquad#75]
- [x] Methods/Fields done first
 - [x] Add Parameter(s)
 - [x] Remove Parameter(s) - one or all
 - [x] Change Parameter(s) - change one or all with a brand new parameter list
 - [x] Parameter List
 - [ ] Plus button on GUI to increase list size
 - [x] Update GUI to account for parameter lists

 - Primary: @anOrgandroiD
 - Secondary: @abkatz33
 - Size: M
 - Actual Size: 
 - Actual Time:

**Comment by anOrgandroiD** [comment]
parameter updates are a ok!
